spring.datasource.url=jdbc:postgresql://localhost:5432/foodTruckDb
spring.datasource.username=postgres
spring.datasource.password=1327

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true